// Licensed under the Apache 2.0 License. See LICENSE.txt in the project root for more information.

namespace ElasticLinq.Request.Criteria
{
    /// <summary>
    /// Represents placeholders for constant values in the criteria tree until they
    /// can be reduced by <see cref="ConstantCriteriaFilterReducer"/>.
    /// </summary>
    /// <remarks>
    /// These are generated by constant expressions within Where or Query clauses.
    /// </remarks>
    sealed class ConstantCriteria : ICriteria
    {
        readonly object constantValue;

        /// <summary>
        /// The <see cref="ConstantCriteria"/> that represents <c>false</c>.
        /// </summary>
        internal static readonly ConstantCriteria False = new ConstantCriteria(false);

        /// <summary>
        /// The <see cref="ConstantCriteria"/> that represents <c>true</c>.
        /// </summary>
        internal static readonly ConstantCriteria True = new ConstantCriteria(true);

        /// <summary>
        /// Initializes a new instance of the <see cref="ConstantCriteria"/> class.
        /// </summary>
        /// <param name="constantValue">Constant value to be represented by this criteria.</param>
        ConstantCriteria(object constantValue)
        {
            this.constantValue = constantValue;
        }

        /// <inheritdoc/>
        public string Name => constantValue?.ToString() ?? "null";

        /// <inheritdoc/>
        public override string ToString()
        {
            return Name;
        }
    }
}